### ISSUE TITLE
Counts are not good

### ISSUE THREAD

**Issue by ghost** [BillSJC/gorm-pageable#1]
Hi,

Hope you are all well !

I tested your package on Post model where the limit is 100 and request the page 3, knowing that I have only 200 posts, and the resp returned wrong values or empty ones.

It returned:
```bash
PageNow: 3
PageCount: 0
FirstPage: false
LastPage: false
RawCount:
RawPerPage:
FirstPage: false
Empty:
```

Should have (if I am not wrong):
```bash
PageNow: 3
PageCount: 2
FirstPage: false
LastPage: true
RawCount: ?
RawPerPage: ?
FirstPage: false
Empty: true
```

Any ways to fix it ? or any inputs on that ?

Cheers,
X

**Comment by BillSJC** [comment]
Hi! i try to reenact the question you talk about, but i cannot find the situation  that may lead `PageCount ` became 0 , when i try to request  next page of the last page , it gives me the right data, here is the screenshot

![image](https://user-images.githubusercontent.com/13696311/75702298-2de35100-5cf0-11ea-8b7a-9346c2bc862d.png)

 Dose the param `RawCount` also became 0 at the same time ? The `PageCount` is calculated by `RawCount` and `rawPerPage`

**Comment by BillSJC** [comment]
One more thing, are u useing the first commit of my code?  I fixded some stupid mistake reltaed to the `pageCount` in my [second commit](https://github.com/BillSJC/gorm-pageable/commit/4b156571757c64c69061c6c06c079818dc356722)

**Comment by ghost** [comment]
Thanks, I will integrate it to my project https://github.com/qorpress/qorpress-example

**Comment by BillSJC** [comment]
Wow, it's my pleasure to see that.
